/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peliculas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author f-er9
 */
public class Formulariopeliculas extends javax.swing.JFrame {

    DefaultListModel modeloLista = new DefaultListModel();
    String id,nombre,director,productora,genero,estreno,calificacion;
   
  
    int[] num = new int[5];
    private static Connection conn=null;
    private static String user ="hr4";
    private static String pass ="ferdo953";
    private static String url = "jdbc:oracle:thin:@localhost:1521:XE";
    PreparedStatement ps;
    ResultSet rs;
    
    public static Connection getConection(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn= DriverManager.getConnection(url,user,pass);
            conn.setAutoCommit(false);
            
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, "Conexion erronea E");
        }
        return conn;
    }
    public Formulariopeliculas() {
        initComponents();
        this.setLocationRelativeTo(null); 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Director");
        model.addColumn("Productora");
        model.addColumn("Genero");
        model.addColumn("Estreno");
        model.addColumn("Caliicacion");
        
        tablavts.setModel(model);
        String datos[] = new String[10];
        try {
            Connection con = getConection();
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM peliculas");
            rs = ps.executeQuery();
            System.out.println("hola");
            while(rs.next()){//Se hace el llenado de la tabla con los datos que se obtienen  de la consulta
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                model.addRow(datos);
            }
            tablavts.setModel(model);

            if(tablavts.getModel().getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO NINGUNA COINCIDENCIA","AVISO",JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error en la consulta..." + ex.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablavts = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("INVENTARIO PELICULAS");

        tablavts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablavts);

        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\EasyQuery\\Imagenes\\eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon("C:\\EasyQuery\\Imagenes\\Modificar.png")); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(873, 873, 873))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que deseas eliminar la columa seleccionada?", "CONSULTA!", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            int FilaSelec=tablavts.getSelectedRow();
            if(FilaSelec>=0){
                id=tablavts.getValueAt(FilaSelec, 0).toString();
                nombre=tablavts.getValueAt(FilaSelec, 1).toString();
                director=tablavts.getValueAt(FilaSelec, 2).toString();
                productora=tablavts.getValueAt(FilaSelec, 3).toString();
                genero=tablavts.getValueAt(FilaSelec, 4).toString();
                estreno=tablavts.getValueAt(FilaSelec, 3).toString();
                calificacion=tablavts.getValueAt(FilaSelec, 4).toString();

                Connection con = null;

                try{

                    con = getConection();
                    ps = (PreparedStatement) con.prepareStatement("DELETE FROM peliculas WHERE id=?");
                    ps.setInt(1, Integer.parseInt(id));

                    int res = ps.executeUpdate();

                    if(res > 0){
                        con.close();
                        con = getConection();
                        ps = (PreparedStatement) con.prepareStatement("DELETE FROM empleados WHERE id_emp=?");
                        ps.setInt(1, Integer.parseInt(id));
                        res = ps.executeUpdate();
                        if(res>0){
                            JOptionPane.showMessageDialog(null, "Empleado y Usuario Eliminados exitosamente");
                        }else{
                            JOptionPane.showMessageDialog(null, "Error al eliminar al empleado");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar Empleado");

                    }

                    con.close();

                } catch(Exception e){
                    System.err.println(e);
                }

            }else{
                JOptionPane.showMessageDialog(null, "Debes seleccionar la columna a eliminar");
            }}
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que deseas modificar la columa seleccionada?", "CONSULTA!", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            int FilaSelec=tablavts.getSelectedRow();
            if(FilaSelec>=0){
                id=tablavts.getValueAt(FilaSelec, 0).toString();
                nombre=tablavts.getValueAt(FilaSelec, 1).toString();
                director=tablavts.getValueAt(FilaSelec, 2).toString();
                productora=tablavts.getValueAt(FilaSelec, 3).toString();
                genero=tablavts.getValueAt(FilaSelec, 4).toString();
                estreno=tablavts.getValueAt(FilaSelec, 3).toString();
                calificacion=tablavts.getValueAt(FilaSelec, 4).toString();
                Connection con = null;

                try{

                    con = getConection();
                    ps = (PreparedStatement) con.prepareStatement("UPDATE peliculas SET nombre=?, director=?, productora=?, genero=?, estreno=?, caliicacion=? WHERE id=?");
                    ps.setString(1, nombre);
                    ps.setString(2, director);
                    ps.setString(3, productora);
                    ps.setString(4, genero);
                    ps.setInt(5, Integer.parseInt(estreno));
                    ps.setString(6,calificacion);
                    ps.setString(7,id);
                    int res = ps.executeUpdate();

                    if(res > 0){
                        JOptionPane.showMessageDialog(null, "Persona Modificada");
                        dispose();
                        Formulariopeliculas f=new Formulariopeliculas();
                        f.show();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al Modificar persona");
                        dispose();
                        Formulariopeliculas f=new Formulariopeliculas();
                        f.show();

                    }

                    con.close();

                } catch(Exception e){
                    System.err.println(e);
                }

            }else{
                JOptionPane.showMessageDialog(null, "Debes seleccionar la columna a modificar");
            }}
    }//GEN-LAST:event_btnmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulariopeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulariopeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulariopeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulariopeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulariopeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablavts;
    // End of variables declaration//GEN-END:variables
}
